### ISSUE TITLE
Design to do: Modal window for red footnotes

### ISSUE THREAD

**Issue by jgg3mb** [Dash-Amerikan/dash-american#12]
This ticket relates to producing a modal window once a user clicks on one of the red footnotes. For an example of this effect, visit the Grantland website (http://grantland.com/features/blades-of-glory/). Who wants to work on this?
![grantland footnote](https://cloud.githubusercontent.com/assets/22477253/24218560/1b133422-0f1a-11e7-8f33-f96372d69e80.JPG)
![grantland footnote window](https://cloud.githubusercontent.com/assets/22477253/24218587/2e7f8bb4-0f1a-11e7-8bcd-3cb97c991b84.JPG)

**Comment by alycollins** [comment]
Sarah you said that you were interested in looking jquery to do this :).

**Comment by sarahrahrah** [comment]
Yes! :)

**Comment by jgg3mb** [comment]
So I worked on this today and didn't make much progress. I did realize, however, that I'll approach it again without trying to utilize any external libraries like Bootstrap or jQuery. I'll going to try and make it from scratch, after all, using just HTML and CSS. When I try again, this site is going to be my starting point:
http://www.webdesignerdepot.com/2012/10/creating-a-modal-window-with-html5-and-css3/

**Comment by jgg3mb** [comment]
I also inspected the modal window from the Grantland website. Based on what I found, I started formatting the pop-up window in CSS. It's called .footnote-box.

**Comment by jgg3mb** [comment]
Jeremy, since I'm a bit stone-walled on this, could you lend a suggestion or two? It would help us get started on the other modal windows we'd like to create...

**Comment by sarahrahrah** [comment]
I just pushed the new version that includes a pop up modal window on page load.  I think I'm kind of understanding how to do this now, and I can help with the other modal windows. This tutorial is helpful: 

https://www.w3schools.com/howto/howto_css_modals.asp

as is a section in the book jQuery 2.0 Development Cookbook entitled "Creating a Modal Popup"

**Comment by jgg3mb** [comment]
Once I get the distinctive "X" for the welcome window I will also put it in here.
![modal window x](https://cloud.githubusercontent.com/assets/22477253/24668581/6e0d80a4-1935-11e7-9148-1a43295b9418.JPG)

**Comment by jgg3mb** [comment]
I did some messing around with the footnote box, I think it looks better now. Leaving behind the idea of copying the Kardashian "X."
