### ISSUE TITLE
Design to do: Pop up welcome screen

### ISSUE THREAD

**Issue by jgg3mb** [Dash-Amerikan/dash-american#15]
This ticket relates to producing a pop up welcome screen like the one that greets users on the DASH site (https://shopdashonline.com/).
![dash welcome window](https://cloud.githubusercontent.com/assets/22477253/24219087/fe3fa84c-0f1b-11e7-927f-c661d679b905.JPG)

**Comment by sarahrahrah** [comment]
I made something like this.  It might need a little tweaking, but it looks pretty similar.

**Comment by jgg3mb** [comment]
Awesome. I will try to play with it tomorrow and try to overlay some images, like it is in the top half of the window. I'll also put in some dummy text. Also try to get an "X" that looks similar....

**Comment by jgg3mb** [comment]
Done!
