### ISSUE TITLE
Create an image archive for use in website design 

### ISSUE THREAD

**Issue by jgg3mb** [Dash-Amerikan/dash-american#6]
I plan on gleaning the .json files of Tweets from Jordan for http://twitpic.com or http://bit.ly strings that may link to images, download them, and put them all up in a shared folder in Box for common use.

**Comment by jgg3mb** [comment]
Finished compiling the Tweets with twitpics attached (also had to clean up the data set a bit). I just posted it to the shared folder: 

https://virginia.box.com/s/iykm5bu8rm1xx9vgswvnhws5zs2tw8a8

Any thoughts about how to write a script that would download the .jpegs from the URLs, automatically?

**Comment by jdbuysse** [comment]
I'm still going to work on a webscraping script to do this, but I realized this morning that it would be very easy (with a firefox addon) to download twitpic/instagram pages in thumbnail size. Wouldn't be ideal but we have that as a backup if we run into any problems and thumbnails are enough for our design goals

**Comment by jgg3mb** [comment]
Interesting! Is this plug-in close to what you're talking about? It's called ThumbsDown:
https://bitbucket.org/atte-kemppila/thumbsdown/overview
You still need to write a script to move from thumbnails to full-size .jpegs, however...

**Comment by jgg3mb** [comment]
Thanks for doing this! Happy to have so many images!

**Comment by alycollins** [comment]
Sorry I misread this issue! Not sure if the result was achieved with this: https://virginia.app.box.com/files/0/f/22599656484/Kardashian_image_cache

or not?

**Comment by jdbuysse** [comment]
Those are some of the instagram posts. I'm going to upload more, and also try to do the same with twitpic maybe (if it would still be useful)

**Comment by alycollins** [comment]
cool!
