### ISSUE TITLE
Instagram photos?

### ISSUE THREAD

**Issue by jgg3mb** [Dash-Amerikan/dash-american#7]
As I look for http://twitpic.com or http://bit.ly links to images in the Kardashian Twitter feed, can someone else look for ways to scrape all the images off of individual family member's Instagram accounts?

**Comment by jdbuysse** [comment]
I'm doing this today, should have more Kardashian pictures than we know what to do with soon. Relatedly, do you know how much storage space we have on the box account? I could put them there but don't want to use all our storage in case it is limited

**Comment by jgg3mb** [comment]
Awesome! I think we've got plenty of space in Box. I've got all my files, ever, on my personal account and I keep tons of .jpegs (art historian!). Here's the folder I created to house the image archive for the website:

https://virginia.box.com/s/82pnfxdlcx38ccaespp856xa130duzwr

**Comment by jgg3mb** [comment]
Likewise, we've finished this so closing...
